services:
  - type: web
    name: AI-Powered-Sustainable-Packaging-Recommendation-System
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
